server:
  port: 9070

spring:
  application:
    name: QUIZSERVICE2

  datasource:
    url: jdbc:postgresql://localhost:5432/quiz
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka