server:
  port: 9090

spring:
  application:
    name: REGISTERSERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/netflix
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka